title: "Clarisse Diandra"
author: "Clarisse Diandra"
description: "&copy; Clarisse Diandra 2024"
permalink: /:categories/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y"         # default: "%B %d, %Y"

# Layout

show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

icons:                     # additional icons that can be used in the text across the website
  - {icon: keyboard}
  - {icon: location-dot}
  - {icon: c}
  - {icon: file}
  - {icon: dna}
  - {icon: flask}

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "commercial.html", icon: "sack-dollar", title: "Commercial Projects"}
  - {file: "personal.html", icon: "person", title: "Personal Projects"}
  - {file: "university.html", icon: "building-columns", title: "University Projects"}
  # - {file: "categories.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {icon: envelope, url: "mailto:clarisse14diandra@gmail.com"}
  - {icon: linkedin, url: "https://www.linkedin.com/in/clarissediandra"}
  - {icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
